# Market Data API

Schwab's Trader API has the ability to retrieve market data for given positions. The essential data required to perform a technical analysis on a given here.

<span style="color:red">
    To use the notebook, ensure that _auth is running.
</span>.

In [1]:
import json
import pprint
import numpy as np
import pandas as pd
import settings.schwab as schwab
from datetime import datetime, date

In [2]:
pp = pprint.PrettyPrinter(indent=4)

**Authenticate**

In [3]:
auth = schwab.Authenticator()

## Load Portfolio

Positions to track within the given portfolio are stored in a json file for easy storage and retrieval. A few indexes are included as a benchmark.

In [4]:
portfolio = open('./symbols.json')
instruments = json.load(portfolio)
portfolio.close()

In [5]:
for symbol in instruments.keys():
    print('{:8s} | {}'.format(symbol, instruments[symbol]))

DJIA     | Dow Jones Industrial Average
SWPPX    | Schwab S&P 500 Index Fund
SWANX    | Schwab Core Equity Fund
SFLNX    | Schwab Fundamental US Large Company Index Fund

### Analyze Positions

Market data can now be pulled from the Schwab API endpoints. Select a ticker to analyze:

In [6]:
symbol = input('ticker:')

ticker: SWPPX

In [7]:
position = schwab.Position(auth, symbol)
position.get_quotes()

{'SWPPX': {'assetMainType': 'MUTUAL_FUND',
  'assetSubType': 'OEF',
  'realtime': True,
  'ssid': 871601704,
  'symbol': 'SWPPX',
  'fundamental': {'avg10DaysVolume': 0.0,
   'avg1YearVolume': 0.0,
   'declarationDate': '2023-12-08T05:00:00Z',
   'divAmount': 1.0464,
   'divExDate': '2023-12-08T05:00:00Z',
   'divFreq': 1,
   'divPayAmount': 1.0464,
   'divPayDate': '2023-12-08T05:00:00Z',
   'divYield': 1.28645,
   'eps': 0.0,
   'fundLeverageFactor': 0.0,
   'lastEarningsDate': '2024-01-02T05:00:00Z',
   'nextDivExDate': '2024-12-09T05:00:00Z',
   'nextDivPayDate': '2024-12-09T05:00:00Z',
   'peRatio': 0.0},
  'quote': {'52WeekHigh': 82.54,
   '52WeekLow': 63.83,
   'lastPrice': 82.45,
   'closePrice': 82.52,
   'nAV': 82.45,
   'netChange': -0.07,
   'netPercentChange': -0.08482792,
   'securityStatus': 'Normal',
   'tradeTime': 1717800300000},
  'reference': {'cusip': '808509855',
   'description': 'SCHWAB S&P 500 INDEX',
   'exchange': '3',
   'exchangeName': 'Mutual Fund'}}}

### Pricing History

The Market Data API is working, but I'm still working through some of the parameters and response conditions. Start by sending a start and end date in isoformat.

In [8]:
start_date = date(2024, 4, 1).isoformat()
end_date = datetime.now().isoformat()

The pricing history that is given in the response seems to be somewhat inconsistent. I think using the [yfinance](https://pypi.org/project/yfinance/) package would be more reliable for conducting market analysis at the moment, until the parameters are figured out and simplified.

<span style="color:red">
    I was expecting to pull in a daily candle from 4/1 until 6/10. I noticed that switching the ticker symbol provided different results with the same date range applied.
</span>.

In [9]:
position.get_price_history(start_date, end_date)
position.price_history

    open   high    low  close  volume            datetime
0  81.75  81.75  81.75  81.75       0 2024-05-24 22:13:00
1  81.77  81.77  81.77  81.77       0 2024-05-28 22:06:00
2  81.17  81.17  81.17  81.17       0 2024-05-29 22:07:00
3  80.69  80.69  80.69  80.69       0 2024-05-30 22:13:00
4  81.34  81.34  81.34  81.34       0 2024-05-31 22:12:00
5  81.44  81.44  81.44  81.44       0 2024-06-03 22:19:00
6  81.57  81.57  81.57  81.57       0 2024-06-04 22:22:00
7  82.54  82.54  82.54  82.54       0 2024-06-05 22:01:00
8  82.52  82.52  82.52  82.52       0 2024-06-06 22:06:00
9  82.45  82.45  82.45  82.45       0 2024-06-07 22:07:00

In [10]:
position = schwab.Position(auth, 'DJIA')
position.get_price_history(start_date, end_date)
position.price_history

        open     high      low    close  volume            datetime
0    22.0700  22.0700  22.0700  22.0700     257 2024-05-24 13:30:00
1    22.1500  22.1500  22.1500  22.1500     113 2024-05-24 13:41:00
2    22.0900  22.0900  21.9900  21.9901    3376 2024-05-24 14:25:00
3    21.9800  22.0800  21.9708  21.9708    1700 2024-05-24 14:28:00
4    22.0300  22.0300  22.0300  22.0300     802 2024-05-24 14:34:00
..       ...      ...      ...      ...     ...                 ...
290  21.9500  21.9500  21.9500  21.9500     100 2024-06-07 19:05:00
291  21.9850  21.9850  21.9850  21.9850    1750 2024-06-07 19:11:00
292  21.9101  21.9101  21.9101  21.9101    3269 2024-06-07 19:25:00
293  21.9850  21.9850  21.9850  21.9850     600 2024-06-07 19:29:00
294  22.0000  22.0000  22.0000  22.0000     100 2024-06-07 20:00:00

[295 rows x 6 columns]